# Generated by Django 4.1.2 on 2022-11-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('cr_limit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('territory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=30)),
                ('p_name', models.CharField(max_length=100)),
                ('UOM', models.CharField(max_length=10)),
                ('tp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_code', models.CharField(max_length=10)),
                ('p_name', models.CharField(max_length=100)),
                ('UOM', models.CharField(max_length=10)),
                ('order_qty', models.IntegerField()),
                ('bonus_qty', models.IntegerField()),
                ('status', models.IntegerField()),
                ('sdp', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=20)),
                ('territory', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=300)),
                ('effective_date', models.DateField()),
                ('entry_date', models.DateField()),
            ],
        ),
    ]
