# Generated by Django 4.1.2 on 2022-11-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=30)),
                ('p_name', models.CharField(max_length=100)),
                ('UOM', models.CharField(max_length=10)),
                ('tp', models.IntegerField()),
                ('order_qty', models.IntegerField()),
                ('bonus_qty', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
